# Generated by Django 3.1.7 on 2021-03-18 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('statement', models.CharField(blank=True, max_length=200, null=True)),
                ('demand', models.CharField(max_length=200)),
                ('input_data', models.CharField(max_length=200)),
                ('output_data', models.CharField(max_length=200)),
                ('restrictions', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.CharField(max_length=200)),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='date published')),
                ('x', models.DateField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
    ]
