# Generated by Django 3.1.7 on 2021-03-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_problem_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='default_code',
            field=models.CharField(default='', max_length=800),
        ),
    ]
