# Generated by Django 3.1.7 on 2021-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_problem_default_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
